version: '3.7'

volumes:
  node_modules: {}

services:
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: nutual_frontend_flask
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    ports:
      - 5173:5173
    environment:
      CHOKIDAR_USEPOLLING: 'true'
      WATCHPACK_POLLING: 'true'
    command: npm run dev -- --host
    restart: on-failure
